### ISSUE TITLE
Showing error on BackendConfig

### ISSUE THREAD

**Issue by WLun001** [GoogleCloudPlatform/cloud-code-intellij#2713]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 20.1.3
- OS: MacOS 10.15.2

Currently on `BackendConfig`, it will detect as error and show red lines on IDE

Backend Config
```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: my-bsc-backendconfig
spec:
  timeoutSec: 600
  connectionDraining:
    drainingTimeoutSec: 60

```
![image](https://user-images.githubusercontent.com/23547929/74641381-27ab8b80-51ac-11ea-86a8-a52053d27649.png)

**Comment by WLun001** [comment]
Same goes to ManagedCertificate

```yaml
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: sample-certificate
```

![image](https://user-images.githubusercontent.com/23547929/74641795-d780f900-51ac-11ea-96b4-27bb7edd039d.png)

**Comment by etanshaul** [comment]
Hi @WLun001 thanks for reporting. Do you happen to also have the JetBrains Kubernetes plugin installed in addition to Cloud Code? I suspect those errors may be coming from that plugin. If so, the plugin has a way to inject schemas for CRDs: 
https://www.jetbrains.com/help/idea/kubernetes.html#crd

**Comment by WLun001** [comment]
Hi @etanshaul, yes I have JetBrains Kubernetes plugin installed. What is the CRD URLs for `cloud.google.com/v1beta1` and `networking.gke.io/v1beta1` to inject schemas for CRDs?

**Comment by etanshaul** [comment]
@redborian do you have any idea if the schemas for these CRDs are available?

**Comment by patricknelson** [comment]
I came here since I was having a similar issue to @WLun001 with `ManagedCertificate`. I was able to get the IDE to recognize it after dropping in the URL's listed below (directly referencing https://github.com/GoogleCloudPlatform/gke-managed-certs), but unfortunately I couldn't find the CRD's for `BackendConfig` 😕 I guess maybe it's still too new?

**Use these CRD URL's:**

https://raw.githubusercontent.com/GoogleCloudPlatform/gke-managed-certs/master/deploy/managedcertificates-crd.yaml

https://raw.githubusercontent.com/GoogleCloudPlatform/gke-managed-certs/master/deploy/managed-certificate-controller.yaml


![image](https://user-images.githubusercontent.com/4269377/75292469-1a5c5580-57d9-11ea-9c3c-2fa22c9ca481.png)

**Comment by WLun001** [comment]
Thanks @patricknelson, it works for `ManagedCertificate`. I happened to found the repo of `BackendConfig`, but can't find any CRDs

https://github.com/kubernetes/ingress-gce/tree/master/pkg/backendconfig

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2577)

**Comment by jmah-cc** [comment]
We are adding support for a lot of CRDs in our next release, including ManagedCertificate.

**Comment by etanshaul** [comment]
@WLun001 this should be resolved now with the release of Cloud Code `20.8.1` and the enhanced CRD support. You can also point to custom CRD schemas as detailed here: https://cloud.google.com/code/docs/intellij/yaml-editing

Let us know if you have any questions.

**Comment by WLun001** [comment]
@jmah-cc where can I find the CDR to load?

**Comment by etanshaul** [comment]
@WLun001 are you asking specifically about `BackendConfig`? I'm having trouble locating that one myself. `ManagedCertificate` _should_ work automatically out of the box now (without having to point to the schema manually).

@redborian I don't see `BackendConfig` in the CRD catalog. Any idea if we should add it?

**Comment by WLun001** [comment]
@etanshaul `ManagedCertificate` still doesn't work

Cloud code version: `20.8.2-202`

**Comment by fsladkey** [comment]
I'm also seeing the issue with `ManagedCertificate`. We'll look into why that isn't working out of the box.

In the meantime you can manually add the CRD to "CRD Schema locations" here. The URL I used was `https://github.com/GoogleCloudPlatform/gke-managed-certs/blob/master/deploy/managedcertificates-crd.yaml`.

<img width="994" alt="Screen Shot 2020-09-01 at 3 56 17 PM" src="https://user-images.githubusercontent.com/12353283/91899874-cccf1280-ec6b-11ea-84ae-efd6162dfe4a.png">

And you should get autocomplete etc
<img width="769" alt="Screen Shot 2020-09-01 at 3 56 24 PM" src="https://user-images.githubusercontent.com/12353283/91899955-f2f4b280-ec6b-11ea-8e31-ec0a4df6adc3.png">

The same strategy should work for `BackendConfig`, unfortunately I don't know where to find the correct CRD to point it at.
